ALTER TABLE "guests"
  ADD COLUMN IF NOT EXISTS "street_address" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "address_line_2" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "city" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "county" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "postcode" VARCHAR(30);
