ALTER TYPE "AmenityIcon" ADD VALUE IF NOT EXISTS 'CABLE_CHANNELS';
ALTER TYPE "AmenityIcon" ADD VALUE IF NOT EXISTS 'REFRIGERATOR';
ALTER TYPE "AmenityIcon" ADD VALUE IF NOT EXISTS 'FLAT_SCREEN_TV';
ALTER TYPE "AmenityIcon" ADD VALUE IF NOT EXISTS 'LINEN';
ALTER TYPE "AmenityIcon" ADD VALUE IF NOT EXISTS 'TELEPHONE';
ALTER TYPE "AmenityIcon" ADD VALUE IF NOT EXISTS 'DRYER';
ALTER TYPE "AmenityIcon" ADD VALUE IF NOT EXISTS 'STREAMING';
ALTER TYPE "AmenityIcon" ADD VALUE IF NOT EXISTS 'SAFETY_DEPOSIT_BOX';
